### PR TITLE
Enable dependabot

### PR DESCRIPTION
**Pull request by NobodyXu**
Signed-off-by: Jiahao XU <Jiahao_XU@outlook.com>

### CODE REVIEW

**Comment by alsuren** [comment]
The Rust side of this only has 3 dependencies or something, so hopefully this won't be too noisy ;-).

The GitHub action side of it won't pick up anything that is in the template. Can you think of an easy way to make that work, or should we just deal with that later?

Also, do you want me to give you merge access, in case I fall behind with dependabot reviews?

**Review by alsuren — APPROVED** [review]

**Comment by NobodyXu** [comment]
> The GitHub action side of it won't pick up anything that is in the template. Can you think of an easy way to make that work, or should we just deal with that later?

Hmmm, maybe we can rename that template if it doesn't work?
I'm not sure, let's deal with this later.

> Also, do you want me to give you merge access, in case I fall behind with dependabot reviews?

I'm willing to help you on merging the dependabot PRs, but I'm not very familiar with this codebase though.

**Comment by alsuren** [comment]
> I'm willing to help you on merging the dependabot PRs, but I'm not very familiar with this codebase though.

That's fine. As long as you care about the project (which you seem to) and you're not planning to do anything intentionally malicious, it'll work out okay. I've sent you an invite.

Eventually I'd like to get to a place where binstall people can jump in and make changes to quickinstall. This doesn't have to happen immediately though, and it doesn't have to be you if you don't want to. I just picked on you because you seem like you care, and I think that's more important than anything else.

**Comment by NobodyXu** [comment]
@alsuren Thank you for trusting me!

**Pull request merged**
